/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'rgb(var(--color-primary) / <alpha-value>)',
          foreground: 'rgb(var(--color-primary-foreground) / <alpha-value>)',
        },
        secondary: {
          DEFAULT: 'rgb(var(--color-secondary) / <alpha-value>)',
          foreground: 'rgb(var(--color-secondary-foreground) / <alpha-value>)',
        },
        background: 'rgb(var(--color-background) / <alpha-value>)',
        foreground: 'rgb(var(--color-foreground) / <alpha-value>)',
        muted: {
          DEFAULT: 'rgb(var(--color-muted) / <alpha-value>)',
          foreground: 'rgb(var(--color-muted-foreground) / <alpha-value>)',
        },
        border: 'rgb(var(--color-border) / <alpha-value>)',
        destructive: {
          DEFAULT: 'rgb(var(--color-destructive) / <alpha-value>)',
          foreground: 'rgb(var(--color-destructive-foreground) / <alpha-value>)',
        },
        success: {
          DEFAULT: 'rgb(var(--color-success) / <alpha-value>)',
          foreground: 'rgb(var(--color-success-foreground) / <alpha-value>)',
        },
        warning: {
          DEFAULT: 'rgb(var(--color-warning) / <alpha-value>)',
          foreground: 'rgb(var(--color-warning-foreground) / <alpha-value>)',
        },
        brand: {
          navy: '#103460',
          primary: '#5B84B1',
          'primary-dark': '#3D6A94',
          'primary-light': '#E8F1F8',
          'primary-tint': '#F0F6FB',
          title: '#4E7CB0',
          tagline: '#7C99B8',
          muted: '#8E8E8E',
          body: '#4B5563',
          heading: '#1E3A5F',
          skip: '#666666',
          footer: '#999999',
          background: '#F5F7FA',
          surface: '#F9FAFB',
          white: '#FFFFFF',
          border: '#E5E7EB',
          label: '#6B7280',
          secondary: '#6B7280',
          'secondary-dark': '#4B5563',
          indicator: '#D1D5DB',
          track: '#E5E7EB',
          success: '#16A34A',
          'success-light': '#DCFCE7',
          badge: '#E8F1F8',
          'badge-text': '#3D6A94',
          overlay: '#E8ECF0',
          disabled: '#B0C4D8',
          link: '#5B84B1',
          error: '#EF4444',
          circuit: '#0F2744',
        },
      },
      fontFamily: {
        sans: ['Inter-Regular'],
        medium: ['Inter-Medium'],
        semibold: ['Inter-SemiBold'],
        bold: ['Inter-Bold'],
      },
      borderRadius: {
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '24px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        '2xl': '32px',
        '3xl': '40px',
        '4xl': '48px',
        '5xl': '64px',
      },
    },
  },
  plugins: [],
};
