/**
 * Blind B2B marketplace catalog — mirrored from Customer WEBAPP
 * (`Swaroop-Customer-WEBAPP/mock/blind-grades.ts`) for Source.one-style grades.
 * Seller identity is always PRIVATE — no product photography in discovery.
 */

import type {
  MarketAvailabilityBadge,
  MarketParentCategoryId,
  MarketProduct,
  ProductTechnicalSpecs,
} from '@/types/market';

type BlindGradeInput = {
  id: string;
  name: string;
  grade: string;
  gradeCode: string;
  categoryId: MarketParentCategoryId;
  materialType: string;
  subCategory: string;
  description: string;
  price: number;
  origin: string;
  warehouseId: string;
  warehouseLabel: string;
  stock: number;
  moq: number;
  eta: string;
  badge: MarketAvailabilityBadge;
  casNumber: string;
  applications: string[];
  creditEligible: boolean;
  stockStatus: 'in_stock' | 'limited' | 'out_of_stock';
  createdAt: string;
  popularityScore: number;
  supplyOrigin?: 'domestic' | 'imported';
  technicalSpecs: ProductTechnicalSpecs;
  sellerId?: string;
};

function blindGrade(input: BlindGradeInput): MarketProduct {
  return {
    id: input.id,
    name: input.name,
    grade: input.grade,
    price: input.price,
    origin: input.origin,
    stock: input.stock,
    moq: input.moq,
    eta: input.eta,
    category: input.materialType,
    badge: input.badge,
    image: '',
    gradeCode: input.gradeCode,
    categoryId: input.categoryId,
    materialType: input.materialType,
    subCategory: input.subCategory,
    description: input.description,
    warehouseLabel: input.warehouseLabel,
    casNumber: input.casNumber,
    applications: input.applications,
    technicalSpecs: input.technicalSpecs,
    creditEligible: input.creditEligible,
  };
}

/** Comprehensive blind grade catalog — ≥55 SKUs across polymers, chemicals, recycled & oils. */
export const blindGradesMock: MarketProduct[] = [
  // ─── Existing IDs (preserve for deep links / orders / offers) ───────────
  blindGrade({
    id: 'mkt-pp-h110ma',
    name: 'PP Homopolymer Injection Grade',
    grade: 'PP',
    gradeCode: 'PP-IM-110',
    categoryId: 'polymers',
    materialType: 'Polypropylene',
    subCategory: 'Injection Moulding',
    description:
      'High-flow PP homopolymer for thin-wall injection moulding and household applications.',
    price: 94500,
    origin: 'Western India Region',
    warehouseId: 'wh-jamnagar',
    warehouseLabel: 'Western Hub',
    stock: 850,
    moq: 12,
    eta: '2–3 Days',
    badge: 'Fastest Delivery',
    casNumber: '9003-07-0',
    applications: ['Packaging', 'Household Items', 'Industrial Containers'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-07-28T08:00:00.000Z',
    popularityScore: 98,
    supplyOrigin: 'domestic',
    technicalSpecs: { mfi: '11.0 g/10 min', density: '0.900 g/cm³', form: 'Pellets' },
  }),
  blindGrade({
    id: 'mkt-hdpe-f1002',
    name: 'HDPE Film Grade',
    grade: 'HDPE',
    gradeCode: 'HDPE-FL-002',
    categoryId: 'polymers',
    materialType: 'HDPE',
    subCategory: 'Film',
    description: 'Blown film HDPE for flexible packaging, liners and industrial film.',
    price: 91200,
    origin: 'Northern India Region',
    warehouseId: 'wh-bathinda',
    warehouseLabel: 'Northern Hub',
    stock: 1100,
    moq: 18,
    eta: '5–7 Days',
    badge: 'Lowest Cost',
    casNumber: '9002-88-4',
    applications: ['Flexible Packaging', 'Liners', 'Industrial Film'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-07-22T08:00:00.000Z',
    popularityScore: 92,
    supplyOrigin: 'domestic',
    technicalSpecs: { mfi: '0.20 g/10 min', density: '0.952 g/cm³', form: 'Pellets' },
  }),
  blindGrade({
    id: 'mkt-pvc-s65',
    name: 'PVC Suspension S-65',
    grade: 'PVC',
    gradeCode: 'PVC-S-65',
    categoryId: 'polymers',
    materialType: 'PVC',
    subCategory: 'Suspension',
    description: 'Suspension PVC resin for pipe, fittings and rigid profile extrusion.',
    price: 98750,
    origin: 'Western India Region',
    warehouseId: 'wh-dahej',
    warehouseLabel: 'Dahej Hub',
    stock: 40,
    moq: 10,
    eta: '2–4 Days',
    badge: 'Premium Grade',
    casNumber: '9002-86-2',
    applications: ['Pipes', 'Fittings', 'Rigid Profiles'],
    creditEligible: false,
    stockStatus: 'limited',
    createdAt: '2026-07-30T08:00:00.000Z',
    popularityScore: 88,
    supplyOrigin: 'domestic',
    technicalSpecs: { form: 'Powder', kValue: '65', bulkDensity: '0.52 g/cm³' },
  }),
  blindGrade({
    id: 'mkt-hdpe-m6007',
    name: 'HDPE Injection M6007',
    grade: 'HDPE',
    gradeCode: 'HDPE-IM-007',
    categoryId: 'polymers',
    materialType: 'HDPE',
    subCategory: 'Injection Moulding',
    description:
      'Injection moulding HDPE with balanced stiffness and impact for crates and containers.',
    price: 96800,
    origin: 'Western India Region',
    warehouseId: 'wh-hazira',
    warehouseLabel: 'Hazira Hub',
    stock: 620,
    moq: 14,
    eta: '3–5 Days',
    badge: 'Best Value',
    casNumber: '9002-88-4',
    applications: ['Crates', 'Containers', 'Caps'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-07-18T08:00:00.000Z',
    popularityScore: 85,
    supplyOrigin: 'domestic',
    technicalSpecs: { mfi: '7.0 g/10 min', density: '0.960 g/cm³', form: 'Pellets' },
  }),
  blindGrade({
    id: 'mkt-lldpe-f24005',
    name: 'LLDPE Film F24005',
    grade: 'LLDPE',
    gradeCode: 'LLDPE-FL-005',
    categoryId: 'polymers',
    materialType: 'LLDPE',
    subCategory: 'Film',
    description:
      'Linear low-density polyethylene film grade for stretch wrap and agricultural film.',
    price: 98500,
    origin: 'Western India Region',
    warehouseId: 'wh-mundra',
    warehouseLabel: 'Mundra Hub',
    stock: 340,
    moq: 16,
    eta: '3–5 Days',
    badge: 'High Demand',
    casNumber: '25087-34-7',
    applications: ['Stretch Wrap', 'Agricultural Film', 'Pouches'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-07-25T08:00:00.000Z',
    popularityScore: 90,
    supplyOrigin: 'domestic',
    technicalSpecs: { mfi: '0.90 g/10 min', density: '0.920 g/cm³', form: 'Pellets' },
  }),
  blindGrade({
    id: 'mkt-pet-resin',
    name: 'PET Bottle Grade Resin',
    grade: 'PET',
    gradeCode: 'PET-BG-001',
    categoryId: 'polymers',
    materialType: 'PET',
    subCategory: 'Bottle',
    description: 'Bottle-grade PET resin for beverage and edible oil packaging.',
    price: 89200,
    origin: 'Northern India Region',
    warehouseId: 'wh-panipat',
    warehouseLabel: 'Panipat Hub',
    stock: 780,
    moq: 12,
    eta: '4–6 Days',
    badge: 'Lowest Cost',
    casNumber: '25038-59-9',
    applications: ['Beverage Bottles', 'Edible Oil Packaging', 'Jars'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-07-12T08:00:00.000Z',
    popularityScore: 94,
    supplyOrigin: 'domestic',
    technicalSpecs: { iv: '0.80 dl/g', form: 'Chips', moisture: '<0.3%' },
  }),
  blindGrade({
    id: 'mkt-pp-raffia',
    name: 'PP Raffia Grade',
    grade: 'PP',
    gradeCode: 'PP-RF-284',
    categoryId: 'polymers',
    materialType: 'Polypropylene',
    subCategory: 'Raffia',
    description: 'High-tenacity raffia grade for woven sacks and industrial packaging.',
    price: 92800,
    origin: 'Western India Region',
    warehouseId: 'wh-jamnagar',
    warehouseLabel: 'Western Hub',
    stock: 520,
    moq: 15,
    eta: '2–3 Days',
    badge: 'Fastest Delivery',
    casNumber: '9003-07-0',
    applications: ['Woven Sacks', 'FIBC', 'Industrial Packaging'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-07-26T08:00:00.000Z',
    popularityScore: 96,
    supplyOrigin: 'domestic',
    technicalSpecs: { mfi: '3.5 g/10 min', density: '0.905 g/cm³', form: 'Pellets' },
  }),
  blindGrade({
    id: 'mkt-hdpe-pipe',
    name: 'HDPE Pipe Grade PE100',
    grade: 'HDPE',
    gradeCode: 'HDPE-PP-100',
    categoryId: 'polymers',
    materialType: 'HDPE',
    subCategory: 'Pipe',
    description: 'PE100 pipe grade for pressure water and gas distribution networks.',
    price: 102400,
    origin: 'Western India Region',
    warehouseId: 'wh-hazira',
    warehouseLabel: 'Hazira Hub',
    stock: 95,
    moq: 20,
    eta: '5–7 Days',
    badge: 'Limited Stock',
    casNumber: '9002-88-4',
    applications: ['Water Pipes', 'Gas Distribution', 'Conduit'],
    creditEligible: false,
    stockStatus: 'limited',
    createdAt: '2026-07-08T08:00:00.000Z',
    popularityScore: 78,
    supplyOrigin: 'domestic',
    technicalSpecs: {
      mfi: '0.25 g/10 min',
      density: '0.960 g/cm³',
      form: 'Pellets',
      mrs: '10.0 MPa',
    },
  }),
  blindGrade({
    id: 'mkt-pvc-k67',
    name: 'PVC K67 Resin',
    grade: 'PVC',
    gradeCode: 'PVC-K-67',
    categoryId: 'polymers',
    materialType: 'PVC',
    subCategory: 'Flexible Compound',
    description: 'K67 suspension PVC for flexible compounds, cables and calendaring.',
    price: 82000,
    origin: 'Western India Region',
    warehouseId: 'wh-dahej',
    warehouseLabel: 'Dahej Hub',
    stock: 910,
    moq: 10,
    eta: '3–5 Days',
    badge: 'Best Value',
    casNumber: '9002-86-2',
    applications: ['Cables', 'Flexible Compounds', 'Calendaring'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-07-15T08:00:00.000Z',
    popularityScore: 87,
    supplyOrigin: 'domestic',
    technicalSpecs: { form: 'Powder', kValue: '67', bulkDensity: '0.50 g/cm³' },
  }),
  blindGrade({
    id: 'mkt-pc-resin',
    name: 'Polycarbonate Clear Grade',
    grade: 'PC',
    gradeCode: 'PC-CL-210',
    categoryId: 'polymers',
    materialType: 'Polycarbonate',
    subCategory: 'Optical Clear',
    description: 'Optical-clear polycarbonate for sheets, lenses and protective glazing.',
    price: 186500,
    origin: 'Western India Region',
    warehouseId: 'wh-mundra',
    warehouseLabel: 'Mundra Hub',
    stock: 120,
    moq: 8,
    eta: '5–7 Days',
    badge: 'Premium Grade',
    casNumber: '25037-45-0',
    applications: ['Sheets', 'Lenses', 'Protective Glazing'],
    creditEligible: false,
    stockStatus: 'in_stock',
    createdAt: '2026-07-05T08:00:00.000Z',
    popularityScore: 72,
    supplyOrigin: 'imported',
    technicalSpecs: {
      mfi: '10 g/10 min',
      density: '1.20 g/cm³',
      form: 'Pellets',
      transmittance: '89%',
    },
  }),
  blindGrade({
    id: 'mkt-abs-resin',
    name: 'ABS Injection Grade',
    grade: 'ABS',
    gradeCode: 'ABS-IM-150',
    categoryId: 'polymers',
    materialType: 'ABS',
    subCategory: 'Injection Moulding',
    description:
      'Injection-grade ABS with high gloss and impact for appliances and auto interiors.',
    price: 124800,
    origin: 'Northern India Region',
    warehouseId: 'wh-panipat',
    warehouseLabel: 'Panipat Hub',
    stock: 260,
    moq: 12,
    eta: '4–6 Days',
    badge: 'High Demand',
    casNumber: '9003-56-9',
    applications: ['Appliances', 'Automotive Interiors', 'Electronics'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-07-20T08:00:00.000Z',
    popularityScore: 81,
    supplyOrigin: 'domestic',
    technicalSpecs: { mfi: '15 g/10 min', density: '1.05 g/cm³', form: 'Pellets' },
  }),
  blindGrade({
    id: 'mkt-eva-resin',
    name: 'EVA Film Grade',
    grade: 'EVA',
    gradeCode: 'EVA-FL-18',
    categoryId: 'polymers',
    materialType: 'EVA',
    subCategory: 'Film',
    description: 'EVA film grade for solar encapsulant and flexible packaging laminates.',
    price: 118200,
    origin: 'Northern India Region',
    warehouseId: 'wh-bathinda',
    warehouseLabel: 'Northern Hub',
    stock: 55,
    moq: 10,
    eta: '3–5 Days',
    badge: 'Limited Stock',
    casNumber: '24937-78-8',
    applications: ['Solar Encapsulant', 'Flexible Packaging', 'Foams'],
    creditEligible: false,
    stockStatus: 'limited',
    createdAt: '2026-07-10T08:00:00.000Z',
    popularityScore: 70,
    supplyOrigin: 'imported',
    technicalSpecs: {
      mfi: '2.5 g/10 min',
      density: '0.940 g/cm³',
      form: 'Pellets',
      vaContent: '18%',
    },
  }),
  blindGrade({
    id: 'mkt-pp-copolymer',
    name: 'PP Impact Copolymer',
    grade: 'PP',
    gradeCode: 'PP-CP-450',
    categoryId: 'polymers',
    materialType: 'Polypropylene',
    subCategory: 'Impact Copolymer',
    description: 'Impact copolymer polypropylene for automotive bumpers and battery cases.',
    price: 97200,
    origin: 'Western India Region',
    warehouseId: 'wh-jamnagar',
    warehouseLabel: 'Western Hub',
    stock: 430,
    moq: 14,
    eta: '2–3 Days',
    badge: 'Best Value',
    casNumber: '9010-79-1',
    applications: ['Automotive', 'Battery Cases', 'Industrial Parts'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-07-27T08:00:00.000Z',
    popularityScore: 89,
    supplyOrigin: 'domestic',
    technicalSpecs: { mfi: '12 g/10 min', density: '0.900 g/cm³', form: 'Pellets' },
  }),
  blindGrade({
    id: 'mkt-lldpe-rotomold',
    name: 'LLDPE Rotomolding Grade',
    grade: 'LLDPE',
    gradeCode: 'LLDPE-RM-040',
    categoryId: 'polymers',
    materialType: 'LLDPE',
    subCategory: 'Rotomolding',
    description: 'Rotomolding LLDPE for tanks, containers and outdoor equipment.',
    price: 101500,
    origin: 'Western India Region',
    warehouseId: 'wh-hazira',
    warehouseLabel: 'Hazira Hub',
    stock: 180,
    moq: 16,
    eta: '4–6 Days',
    badge: 'Fastest Delivery',
    casNumber: '25087-34-7',
    applications: ['Tanks', 'Containers', 'Outdoor Equipment'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-07-14T08:00:00.000Z',
    popularityScore: 76,
    supplyOrigin: 'domestic',
    technicalSpecs: { mfi: '4.0 g/10 min', density: '0.935 g/cm³', form: 'Powder' },
  }),
  blindGrade({
    id: 'mkt-pet-fiber',
    name: 'PET Fiber Grade',
    grade: 'PET',
    gradeCode: 'PET-FB-065',
    categoryId: 'polymers',
    materialType: 'PET',
    subCategory: 'Fiber',
    description: 'Fiber-grade PET for textile staple and industrial filament yarns.',
    price: 87500,
    origin: 'Western India Region',
    warehouseId: 'wh-dahej',
    warehouseLabel: 'Dahej Hub',
    stock: 640,
    moq: 18,
    eta: '5–7 Days',
    badge: 'Lowest Cost',
    casNumber: '25038-59-9',
    applications: ['Textile Fiber', 'Industrial Yarn', 'Nonwovens'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-07-03T08:00:00.000Z',
    popularityScore: 83,
    supplyOrigin: 'domestic',
    technicalSpecs: { iv: '0.64 dl/g', form: 'Chips', moisture: '<0.4%' },
  }),
  blindGrade({
    id: 'mkt-toluene',
    name: 'Toluene Industrial Grade',
    grade: 'TOL',
    gradeCode: 'SOL-TOL-99',
    categoryId: 'chemicals',
    materialType: 'Toluene',
    subCategory: 'Aromatic Solvent',
    description: 'High-purity toluene solvent for coatings, adhesives and chemical synthesis.',
    price: 78500,
    origin: 'Western India Region',
    warehouseId: 'wh-jamnagar',
    warehouseLabel: 'Western Hub',
    stock: 420,
    moq: 10,
    eta: '3–5 Days',
    badge: 'Best Value',
    casNumber: '108-88-3',
    applications: ['Coatings', 'Adhesives', 'Chemical Synthesis'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-07-21T08:00:00.000Z',
    popularityScore: 74,
    supplyOrigin: 'domestic',
    technicalSpecs: { purity: '99.5%', form: 'Liquid', boilingPoint: '110.6 °C' },
  }),
  blindGrade({
    id: 'mkt-meg',
    name: 'Mono Ethylene Glycol',
    grade: 'MEG',
    gradeCode: 'CHM-MEG-FG',
    categoryId: 'chemicals',
    materialType: 'MEG',
    subCategory: 'Glycol',
    description: 'Fiber-grade MEG for polyester production and antifreeze formulations.',
    price: 72200,
    origin: 'Western India Region',
    warehouseId: 'wh-mundra',
    warehouseLabel: 'Mundra Hub',
    stock: 980,
    moq: 20,
    eta: '4–6 Days',
    badge: 'Lowest Cost',
    casNumber: '107-21-1',
    applications: ['Polyester', 'Antifreeze', 'Resins'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-07-19T08:00:00.000Z',
    popularityScore: 80,
    supplyOrigin: 'domestic',
    technicalSpecs: { purity: '99.8%', form: 'Liquid', density: '1.113 g/cm³' },
  }),
  blindGrade({
    id: 'mkt-dop',
    name: 'DOP Plasticizer',
    grade: 'DOP',
    gradeCode: 'ADD-DOP-99',
    categoryId: 'additives',
    materialType: 'Plasticizer',
    subCategory: 'Phthalate',
    description: 'Di-octyl phthalate plasticizer for flexible PVC compounds and cables.',
    price: 112000,
    origin: 'Northern India Region',
    warehouseId: 'wh-bathinda',
    warehouseLabel: 'Northern Hub',
    stock: 210,
    moq: 8,
    eta: '3–5 Days',
    badge: 'High Demand',
    casNumber: '117-81-7',
    applications: ['Flexible PVC', 'Cables', 'Flooring'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-07-16T08:00:00.000Z',
    popularityScore: 77,
    supplyOrigin: 'domestic',
    technicalSpecs: { purity: '99.5%', form: 'Liquid', viscosity: '80 cP @ 20°C' },
  }),
  blindGrade({
    id: 'mkt-cao-stabilizer',
    name: 'Ca-Zn Stabilizer',
    grade: 'CZ-50',
    gradeCode: 'ADD-CZ-50',
    categoryId: 'additives',
    materialType: 'Stabilizer',
    subCategory: 'Heat Stabilizer',
    description: 'Calcium-zinc heat stabilizer for non-toxic PVC pipe and profile compounds.',
    price: 145000,
    origin: 'Western India Region',
    warehouseId: 'wh-dahej',
    warehouseLabel: 'Dahej Hub',
    stock: 75,
    moq: 5,
    eta: '5–7 Days',
    badge: 'Premium Grade',
    casNumber: 'Mixture',
    applications: ['PVC Pipes', 'Profiles', 'Medical Compounds'],
    creditEligible: false,
    stockStatus: 'limited',
    createdAt: '2026-07-11T08:00:00.000Z',
    popularityScore: 65,
    supplyOrigin: 'domestic',
    technicalSpecs: { form: 'Powder', metalContent: 'Ca+Zn 8–12%', ash: '<2%' },
  }),
  blindGrade({
    id: 'mkt-base-oil-sn150',
    name: 'Base Oil SN 150',
    grade: 'SN150',
    gradeCode: 'BO-GI-150',
    categoryId: 'base-oils',
    materialType: 'Base Oil',
    subCategory: 'Group I',
    description: 'Group I SN 150 base oil for automotive and industrial lubricant blending.',
    price: 72500,
    origin: 'Western India Region',
    warehouseId: 'wh-jamnagar',
    warehouseLabel: 'Western Hub',
    stock: 560,
    moq: 15,
    eta: '3–5 Days',
    badge: 'Best Value',
    casNumber: '64742-52-5',
    applications: ['Automotive Lubricants', 'Industrial Oils', 'Greases'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-07-24T08:00:00.000Z',
    popularityScore: 79,
    supplyOrigin: 'domestic',
    technicalSpecs: { viscosity: '28–32 cSt @ 40°C', form: 'Liquid', vi: '95+' },
  }),
  blindGrade({
    id: 'mkt-base-oil-n500',
    name: 'Base Oil N 500',
    grade: 'N500',
    gradeCode: 'BO-GII-500',
    categoryId: 'base-oils',
    materialType: 'Base Oil',
    subCategory: 'Group II',
    description: 'Group II N 500 base stock for high-performance engine oil formulations.',
    price: 79800,
    origin: 'Northern India Region',
    warehouseId: 'wh-bathinda',
    warehouseLabel: 'Northern Hub',
    stock: 310,
    moq: 12,
    eta: '4–6 Days',
    badge: 'Fastest Delivery',
    casNumber: '64742-54-7',
    applications: ['Engine Oils', 'Hydraulic Fluids', 'Gear Oils'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-07-23T08:00:00.000Z',
    popularityScore: 82,
    supplyOrigin: 'domestic',
    technicalSpecs: { viscosity: '90–110 cSt @ 40°C', form: 'Liquid', vi: '100+' },
  }),
  blindGrade({
    id: 'mkt-base-oil-g3',
    name: 'Group III VHVI 6',
    grade: 'VHVI-6',
    gradeCode: 'BO-GIII-6',
    categoryId: 'base-oils',
    materialType: 'Base Oil',
    subCategory: 'Group III',
    description: 'Group III very high viscosity index base oil for premium synthetic blends.',
    price: 132000,
    origin: 'Western India Region',
    warehouseId: 'wh-mundra',
    warehouseLabel: 'Mundra Hub',
    stock: 140,
    moq: 10,
    eta: '5–7 Days',
    badge: 'Premium Grade',
    casNumber: '72623-87-1',
    applications: ['Synthetic Blends', 'Premium Engine Oils'],
    creditEligible: false,
    stockStatus: 'in_stock',
    createdAt: '2026-07-09T08:00:00.000Z',
    popularityScore: 68,
    supplyOrigin: 'imported',
    technicalSpecs: { viscosity: '30–34 cSt @ 40°C', form: 'Liquid', vi: '120+' },
  }),

  // ─── Additional polymers ────────────────────────────────────────────────
  blindGrade({
    id: 'mkt-ldpe-film',
    name: 'LDPE Film Grade',
    grade: 'LDPE',
    gradeCode: 'LDPE-FL-022',
    categoryId: 'polymers',
    materialType: 'LDPE',
    subCategory: 'Film',
    description: 'Low-density polyethylene film grade for shrink film and heavy-duty bags.',
    price: 95500,
    origin: 'Western India Region',
    warehouseId: 'wh-hazira',
    warehouseLabel: 'Hazira Hub',
    stock: 480,
    moq: 16,
    eta: '3–5 Days',
    badge: 'Best Value',
    casNumber: '9002-88-4',
    applications: ['Shrink Film', 'Heavy-Duty Bags', 'Lamination'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-01T08:00:00.000Z',
    popularityScore: 84,
    supplyOrigin: 'domestic',
    technicalSpecs: { mfi: '0.30 g/10 min', density: '0.922 g/cm³', form: 'Pellets' },
  }),
  blindGrade({
    id: 'mkt-ldpe-injection',
    name: 'LDPE Injection Grade',
    grade: 'LDPE',
    gradeCode: 'LDPE-IM-070',
    categoryId: 'polymers',
    materialType: 'LDPE',
    subCategory: 'Injection Moulding',
    description: 'Injection LDPE for lids, caps and soft moulded components.',
    price: 93800,
    origin: 'Western India Region',
    warehouseId: 'wh-jamnagar',
    warehouseLabel: 'Western Hub',
    stock: 290,
    moq: 12,
    eta: '2–4 Days',
    badge: 'Fastest Delivery',
    casNumber: '9002-88-4',
    applications: ['Lids', 'Caps', 'Soft Components'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-02T08:00:00.000Z',
    popularityScore: 71,
    supplyOrigin: 'domestic',
    technicalSpecs: { mfi: '7.0 g/10 min', density: '0.918 g/cm³', form: 'Pellets' },
  }),
  blindGrade({
    id: 'mkt-pp-thermoform',
    name: 'PP Thermoforming Grade',
    grade: 'PP',
    gradeCode: 'PP-TF-320',
    categoryId: 'polymers',
    materialType: 'Polypropylene',
    subCategory: 'Thermoforming',
    description: 'PP sheet grade for food containers, trays and blister thermoforming.',
    price: 96200,
    origin: 'Western India Region',
    warehouseId: 'wh-mundra',
    warehouseLabel: 'Mundra Hub',
    stock: 350,
    moq: 14,
    eta: '3–5 Days',
    badge: 'High Demand',
    casNumber: '9003-07-0',
    applications: ['Food Containers', 'Trays', 'Blister Packs'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-03T08:00:00.000Z',
    popularityScore: 86,
    supplyOrigin: 'domestic',
    technicalSpecs: { mfi: '2.8 g/10 min', density: '0.905 g/cm³', form: 'Pellets' },
  }),
  blindGrade({
    id: 'mkt-cpvc-pipe',
    name: 'CPVC Pipe Grade',
    grade: 'CPVC',
    gradeCode: 'CPVC-PP-067',
    categoryId: 'polymers',
    materialType: 'CPVC',
    subCategory: 'Pipe',
    description: 'Chlorinated PVC compound feedstock for hot-water and industrial piping.',
    price: 138500,
    origin: 'Western India Region',
    warehouseId: 'wh-dahej',
    warehouseLabel: 'Dahej Hub',
    stock: 160,
    moq: 10,
    eta: '4–6 Days',
    badge: 'Premium Grade',
    casNumber: '68648-82-8',
    applications: ['Hot Water Pipes', 'Industrial Piping', 'Fittings'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-04T08:00:00.000Z',
    popularityScore: 73,
    supplyOrigin: 'domestic',
    technicalSpecs: { form: 'Powder', chlorineContent: '63–69%', kValue: '67' },
  }),
  blindGrade({
    id: 'mkt-hips-sheet',
    name: 'HIPS Sheet Grade',
    grade: 'HIPS',
    gradeCode: 'HIPS-SH-055',
    categoryId: 'polymers',
    materialType: 'HIPS',
    subCategory: 'Sheet Extrusion',
    description: 'High-impact polystyrene for thermoformed packaging and appliance liners.',
    price: 108500,
    origin: 'Northern India Region',
    warehouseId: 'wh-panipat',
    warehouseLabel: 'Panipat Hub',
    stock: 220,
    moq: 12,
    eta: '4–6 Days',
    badge: 'Best Value',
    casNumber: '9003-55-8',
    applications: ['Food Packaging', 'Appliance Liners', 'Displays'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-05T08:00:00.000Z',
    popularityScore: 69,
    supplyOrigin: 'domestic',
    technicalSpecs: { mfi: '3.5 g/10 min', density: '1.04 g/cm³', form: 'Pellets' },
  }),
  blindGrade({
    id: 'mkt-nylon6-extrusion',
    name: 'Nylon 6 Extrusion Grade',
    grade: 'PA6',
    gradeCode: 'PA6-EX-240',
    categoryId: 'polymers',
    materialType: 'Nylon',
    subCategory: 'Extrusion',
    description: 'Polyamide 6 extrusion grade for films, monofilaments and engineering profiles.',
    price: 198000,
    origin: 'Western India Region',
    warehouseId: 'wh-mundra',
    warehouseLabel: 'Mundra Hub',
    stock: 95,
    moq: 5,
    eta: '5–7 Days',
    badge: 'Premium Grade',
    casNumber: '25038-54-4',
    applications: ['Films', 'Monofilaments', 'Engineering Profiles'],
    creditEligible: false,
    stockStatus: 'limited',
    createdAt: '2026-08-06T08:00:00.000Z',
    popularityScore: 64,
    supplyOrigin: 'imported',
    technicalSpecs: { mfi: '2.4 g/10 min', density: '1.13 g/cm³', form: 'Pellets', rv: '2.7' },
  }),
  blindGrade({
    id: 'mkt-nylon66-injection',
    name: 'Nylon 66 Injection Grade',
    grade: 'PA66',
    gradeCode: 'PA66-IM-180',
    categoryId: 'polymers',
    materialType: 'Nylon',
    subCategory: 'Injection Moulding',
    description: 'PA66 injection grade for automotive connectors and electrical housings.',
    price: 225000,
    origin: 'Western India Region',
    warehouseId: 'wh-hazira',
    warehouseLabel: 'Hazira Hub',
    stock: 70,
    moq: 5,
    eta: '6–8 Days',
    badge: 'Premium Grade',
    casNumber: '32131-17-2',
    applications: ['Automotive Connectors', 'Electrical Housings', 'Gears'],
    creditEligible: false,
    stockStatus: 'limited',
    createdAt: '2026-08-07T08:00:00.000Z',
    popularityScore: 62,
    supplyOrigin: 'imported',
    technicalSpecs: { mfi: '18 g/10 min', density: '1.14 g/cm³', form: 'Pellets' },
  }),
  blindGrade({
    id: 'mkt-pom-copolymer',
    name: 'POM Copolymer Grade',
    grade: 'POM',
    gradeCode: 'POM-CP-090',
    categoryId: 'polymers',
    materialType: 'POM',
    subCategory: 'Engineering',
    description: 'Acetal copolymer for precision gears, clips and low-friction mechanical parts.',
    price: 168000,
    origin: 'Western India Region',
    warehouseId: 'wh-mundra',
    warehouseLabel: 'Mundra Hub',
    stock: 110,
    moq: 6,
    eta: '5–7 Days',
    badge: 'High Demand',
    casNumber: '24969-26-4',
    applications: ['Gears', 'Clips', 'Mechanical Parts'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-08T08:00:00.000Z',
    popularityScore: 67,
    supplyOrigin: 'imported',
    technicalSpecs: { mfi: '9.0 g/10 min', density: '1.41 g/cm³', form: 'Pellets' },
  }),
  blindGrade({
    id: 'mkt-tpu-shore85a',
    name: 'TPU Shore 85A',
    grade: 'TPU',
    gradeCode: 'TPU-85A-01',
    categoryId: 'polymers',
    materialType: 'TPU',
    subCategory: 'Elastomer',
    description: 'Thermoplastic polyurethane Shore 85A for footwear, hoses and flexible cables.',
    price: 242000,
    origin: 'Western India Region',
    warehouseId: 'wh-dahej',
    warehouseLabel: 'Dahej Hub',
    stock: 45,
    moq: 4,
    eta: '6–8 Days',
    badge: 'Limited Stock',
    casNumber: 'Mixture',
    applications: ['Footwear', 'Hoses', 'Flexible Cables'],
    creditEligible: false,
    stockStatus: 'limited',
    createdAt: '2026-08-09T08:00:00.000Z',
    popularityScore: 58,
    supplyOrigin: 'imported',
    technicalSpecs: { hardness: '85 Shore A', density: '1.18 g/cm³', form: 'Pellets' },
  }),
  blindGrade({
    id: 'mkt-hdpe-blow',
    name: 'HDPE Blow Moulding Grade',
    grade: 'HDPE',
    gradeCode: 'HDPE-BM-550',
    categoryId: 'polymers',
    materialType: 'HDPE',
    subCategory: 'Blow Moulding',
    description: 'Blow moulding HDPE for jerry cans, drums and chemical containers.',
    price: 97800,
    origin: 'Western India Region',
    warehouseId: 'wh-jamnagar',
    warehouseLabel: 'Western Hub',
    stock: 410,
    moq: 16,
    eta: '3–5 Days',
    badge: 'Best Value',
    casNumber: '9002-88-4',
    applications: ['Jerry Cans', 'Drums', 'Chemical Containers'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-10T08:00:00.000Z',
    popularityScore: 88,
    supplyOrigin: 'domestic',
    technicalSpecs: { mfi: '0.35 g/10 min', density: '0.954 g/cm³', form: 'Pellets' },
  }),
  blindGrade({
    id: 'mkt-lldpe-metallocene',
    name: 'mLLDPE Metallocene Film',
    grade: 'LLDPE',
    gradeCode: 'mLLDPE-FL-18',
    categoryId: 'polymers',
    materialType: 'LLDPE',
    subCategory: 'Metallocene Film',
    description: 'Metallocene LLDPE for high-clarity cast film and sealant layers.',
    price: 112500,
    origin: 'Western India Region',
    warehouseId: 'wh-mundra',
    warehouseLabel: 'Mundra Hub',
    stock: 195,
    moq: 14,
    eta: '4–6 Days',
    badge: 'Premium Grade',
    casNumber: '25087-34-7',
    applications: ['Cast Film', 'Sealant Layers', 'Lamination'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-11T08:00:00.000Z',
    popularityScore: 75,
    supplyOrigin: 'imported',
    technicalSpecs: { mfi: '1.0 g/10 min', density: '0.918 g/cm³', form: 'Pellets' },
  }),

  // ─── Masterbatch & compounds ────────────────────────────────────────────
  blindGrade({
    id: 'mkt-mb-black',
    name: 'Black Masterbatch 40%',
    grade: 'MB',
    gradeCode: 'MB-BK-40',
    categoryId: 'additives',
    materialType: 'Masterbatch',
    subCategory: 'Black',
    description: 'Carbon black masterbatch 40% for polyolefin pipes, films and mouldings.',
    price: 95000,
    origin: 'Western India Region',
    warehouseId: 'wh-dahej',
    warehouseLabel: 'Dahej Hub',
    stock: 320,
    moq: 5,
    eta: '2–4 Days',
    badge: 'Fastest Delivery',
    casNumber: '1333-86-4',
    applications: ['Pipes', 'Films', 'Mouldings'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-12T08:00:00.000Z',
    popularityScore: 91,
    supplyOrigin: 'domestic',
    technicalSpecs: { form: 'Pellets', pigmentLoading: '40%', carrier: 'PE' },
  }),
  blindGrade({
    id: 'mkt-mb-white',
    name: 'White Masterbatch TiO2 50%',
    grade: 'MB',
    gradeCode: 'MB-WH-50',
    categoryId: 'additives',
    materialType: 'Masterbatch',
    subCategory: 'White',
    description: 'Titanium dioxide white masterbatch for packaging films and injection parts.',
    price: 128000,
    origin: 'Western India Region',
    warehouseId: 'wh-hazira',
    warehouseLabel: 'Hazira Hub',
    stock: 240,
    moq: 5,
    eta: '3–5 Days',
    badge: 'High Demand',
    casNumber: '13463-67-7',
    applications: ['Packaging Films', 'Injection Parts', 'Sheets'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-13T08:00:00.000Z',
    popularityScore: 85,
    supplyOrigin: 'domestic',
    technicalSpecs: { form: 'Pellets', pigmentLoading: '50%', carrier: 'PE' },
  }),
  blindGrade({
    id: 'mkt-mb-uv',
    name: 'UV Stabilizer Masterbatch',
    grade: 'MB',
    gradeCode: 'MB-UV-20',
    categoryId: 'additives',
    materialType: 'Masterbatch',
    subCategory: 'UV Stabilizer',
    description: 'UV stabilizer masterbatch for outdoor agricultural film and pipes.',
    price: 156000,
    origin: 'Western India Region',
    warehouseId: 'wh-jamnagar',
    warehouseLabel: 'Western Hub',
    stock: 85,
    moq: 4,
    eta: '4–6 Days',
    badge: 'Premium Grade',
    casNumber: 'Mixture',
    applications: ['Agricultural Film', 'Outdoor Pipes', 'Geomembranes'],
    creditEligible: false,
    stockStatus: 'limited',
    createdAt: '2026-08-14T08:00:00.000Z',
    popularityScore: 66,
    supplyOrigin: 'domestic',
    technicalSpecs: { form: 'Pellets', activeLoading: '20%', carrier: 'PE' },
  }),
  blindGrade({
    id: 'mkt-compound-pp-talc',
    name: 'PP Talc Filled Compound 20%',
    grade: 'PP',
    gradeCode: 'CMP-PP-T20',
    categoryId: 'polymers',
    materialType: 'Compound',
    subCategory: 'Talc Filled',
    description: '20% talc-filled PP compound for automotive interiors and appliance housings.',
    price: 105500,
    origin: 'Western India Region',
    warehouseId: 'wh-mundra',
    warehouseLabel: 'Mundra Hub',
    stock: 175,
    moq: 10,
    eta: '3–5 Days',
    badge: 'Best Value',
    casNumber: '9003-07-0',
    applications: ['Automotive Interiors', 'Appliance Housings', 'Trims'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-15T08:00:00.000Z',
    popularityScore: 72,
    supplyOrigin: 'domestic',
    technicalSpecs: {
      mfi: '8 g/10 min',
      density: '1.04 g/cm³',
      form: 'Pellets',
      filler: '20% Talc',
    },
  }),
  blindGrade({
    id: 'mkt-compound-abs-fr',
    name: 'ABS Flame Retardant Compound',
    grade: 'ABS',
    gradeCode: 'CMP-ABS-FR',
    categoryId: 'polymers',
    materialType: 'Compound',
    subCategory: 'Flame Retardant',
    description: 'FR ABS compound V-0 for electrical enclosures and consumer electronics.',
    price: 148000,
    origin: 'Northern India Region',
    warehouseId: 'wh-panipat',
    warehouseLabel: 'Panipat Hub',
    stock: 90,
    moq: 8,
    eta: '5–7 Days',
    badge: 'Premium Grade',
    casNumber: '9003-56-9',
    applications: ['Electrical Enclosures', 'Consumer Electronics', 'Switches'],
    creditEligible: false,
    stockStatus: 'limited',
    createdAt: '2026-08-16T08:00:00.000Z',
    popularityScore: 61,
    supplyOrigin: 'domestic',
    technicalSpecs: {
      mfi: '12 g/10 min',
      density: '1.18 g/cm³',
      form: 'Pellets',
      flammability: 'UL94 V-0',
    },
  }),

  // ─── Solvents & chemicals ───────────────────────────────────────────────
  blindGrade({
    id: 'mkt-acetone',
    name: 'Acetone Technical Grade',
    grade: 'ACE',
    gradeCode: 'SOL-ACE-99',
    categoryId: 'chemicals',
    materialType: 'Acetone',
    subCategory: 'Ketone Solvent',
    description: 'Technical acetone for coatings, cleaning and chemical intermediate use.',
    price: 74500,
    origin: 'Western India Region',
    warehouseId: 'wh-dahej',
    warehouseLabel: 'Dahej Hub',
    stock: 520,
    moq: 10,
    eta: '2–4 Days',
    badge: 'Fastest Delivery',
    casNumber: '67-64-1',
    applications: ['Coatings', 'Cleaning', 'Chemical Intermediate'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-17T08:00:00.000Z',
    popularityScore: 88,
    supplyOrigin: 'domestic',
    technicalSpecs: { purity: '99.5%', form: 'Liquid', boilingPoint: '56 °C' },
  }),
  blindGrade({
    id: 'mkt-ipa',
    name: 'Isopropyl Alcohol IPA 99%',
    grade: 'IPA',
    gradeCode: 'SOL-IPA-99',
    categoryId: 'chemicals',
    materialType: 'IPA',
    subCategory: 'Alcohol Solvent',
    description: 'High-purity IPA for pharma intermediates, electronics cleaning and coatings.',
    price: 89500,
    origin: 'Western India Region',
    warehouseId: 'wh-hazira',
    warehouseLabel: 'Hazira Hub',
    stock: 380,
    moq: 8,
    eta: '3–5 Days',
    badge: 'High Demand',
    casNumber: '67-63-0',
    applications: ['Pharma', 'Electronics Cleaning', 'Coatings'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-18T08:00:00.000Z',
    popularityScore: 90,
    supplyOrigin: 'domestic',
    technicalSpecs: { purity: '99.8%', form: 'Liquid', boilingPoint: '82.5 °C' },
  }),
  blindGrade({
    id: 'mkt-mibk',
    name: 'MIBK Solvent Grade',
    grade: 'MIBK',
    gradeCode: 'SOL-MIBK-99',
    categoryId: 'chemicals',
    materialType: 'MIBK',
    subCategory: 'Ketone Solvent',
    description: 'Methyl isobutyl ketone for surface coatings, adhesives and extraction.',
    price: 118000,
    origin: 'Western India Region',
    warehouseId: 'wh-jamnagar',
    warehouseLabel: 'Western Hub',
    stock: 145,
    moq: 8,
    eta: '4–6 Days',
    badge: 'Best Value',
    casNumber: '108-10-1',
    applications: ['Coatings', 'Adhesives', 'Extraction'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-19T08:00:00.000Z',
    popularityScore: 63,
    supplyOrigin: 'domestic',
    technicalSpecs: { purity: '99.0%', form: 'Liquid', boilingPoint: '116 °C' },
  }),
  blindGrade({
    id: 'mkt-mek',
    name: 'MEK Solvent Grade',
    grade: 'MEK',
    gradeCode: 'SOL-MEK-99',
    categoryId: 'chemicals',
    materialType: 'MEK',
    subCategory: 'Ketone Solvent',
    description: 'Methyl ethyl ketone for printing inks, adhesives and surface preparation.',
    price: 102500,
    origin: 'Western India Region',
    warehouseId: 'wh-mundra',
    warehouseLabel: 'Mundra Hub',
    stock: 210,
    moq: 8,
    eta: '3–5 Days',
    badge: 'Best Value',
    casNumber: '78-93-3',
    applications: ['Printing Inks', 'Adhesives', 'Surface Prep'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-20T08:00:00.000Z',
    popularityScore: 70,
    supplyOrigin: 'domestic',
    technicalSpecs: { purity: '99.5%', form: 'Liquid', boilingPoint: '80 °C' },
  }),
  blindGrade({
    id: 'mkt-ethyl-acetate',
    name: 'Ethyl Acetate 99%',
    grade: 'EA',
    gradeCode: 'SOL-EA-99',
    categoryId: 'chemicals',
    materialType: 'Ethyl Acetate',
    subCategory: 'Ester Solvent',
    description: 'Ethyl acetate for flexographic inks, coatings and pharmaceutical extraction.',
    price: 86500,
    origin: 'Western India Region',
    warehouseId: 'wh-dahej',
    warehouseLabel: 'Dahej Hub',
    stock: 450,
    moq: 10,
    eta: '2–4 Days',
    badge: 'Fastest Delivery',
    casNumber: '141-78-6',
    applications: ['Flexo Inks', 'Coatings', 'Pharma Extraction'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-21T08:00:00.000Z',
    popularityScore: 82,
    supplyOrigin: 'domestic',
    technicalSpecs: { purity: '99.5%', form: 'Liquid', boilingPoint: '77 °C' },
  }),
  blindGrade({
    id: 'mkt-benzene',
    name: 'Benzene Pure Grade',
    grade: 'BNZ',
    gradeCode: 'CHM-BNZ-99',
    categoryId: 'chemicals',
    materialType: 'Benzene',
    subCategory: 'Aromatic Intermediate',
    description: 'Pure benzene feedstock for styrene, cumene and chemical synthesis.',
    price: 82500,
    origin: 'Western India Region',
    warehouseId: 'wh-jamnagar',
    warehouseLabel: 'Western Hub',
    stock: 600,
    moq: 20,
    eta: '3–5 Days',
    badge: 'Lowest Cost',
    casNumber: '71-43-2',
    applications: ['Styrene Feedstock', 'Cumene', 'Chemical Synthesis'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-22T08:00:00.000Z',
    popularityScore: 76,
    supplyOrigin: 'domestic',
    technicalSpecs: { purity: '99.9%', form: 'Liquid', boilingPoint: '80.1 °C' },
  }),
  blindGrade({
    id: 'mkt-styrene',
    name: 'Styrene Monomer',
    grade: 'SM',
    gradeCode: 'CHM-SM-99',
    categoryId: 'chemicals',
    materialType: 'Styrene',
    subCategory: 'Monomer',
    description: 'Polymer-grade styrene monomer for PS, ABS and unsaturated polyester resins.',
    price: 98500,
    origin: 'Western India Region',
    warehouseId: 'wh-hazira',
    warehouseLabel: 'Hazira Hub',
    stock: 340,
    moq: 15,
    eta: '3–5 Days',
    badge: 'High Demand',
    casNumber: '100-42-5',
    applications: ['PS', 'ABS', 'UPR'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-23T08:00:00.000Z',
    popularityScore: 87,
    supplyOrigin: 'domestic',
    technicalSpecs: { purity: '99.8%', form: 'Liquid', inhibitor: '10–15 ppm TBC' },
  }),
  blindGrade({
    id: 'mkt-mma',
    name: 'MMA Monomer',
    grade: 'MMA',
    gradeCode: 'CHM-MMA-99',
    categoryId: 'chemicals',
    materialType: 'MMA',
    subCategory: 'Monomer',
    description: 'Methyl methacrylate monomer for acrylic sheets, coatings and adhesives.',
    price: 142000,
    origin: 'Western India Region',
    warehouseId: 'wh-mundra',
    warehouseLabel: 'Mundra Hub',
    stock: 125,
    moq: 8,
    eta: '5–7 Days',
    badge: 'Premium Grade',
    casNumber: '80-62-6',
    applications: ['Acrylic Sheets', 'Coatings', 'Adhesives'],
    creditEligible: false,
    stockStatus: 'in_stock',
    createdAt: '2026-08-24T08:00:00.000Z',
    popularityScore: 68,
    supplyOrigin: 'imported',
    technicalSpecs: { purity: '99.8%', form: 'Liquid', inhibitor: '10–20 ppm MEHQ' },
  }),
  blindGrade({
    id: 'mkt-maleic-anhydride',
    name: 'Maleic Anhydride Flakes',
    grade: 'MA',
    gradeCode: 'CHM-MA-99',
    categoryId: 'chemicals',
    materialType: 'Maleic Anhydride',
    subCategory: 'Intermediate',
    description: 'Maleic anhydride flakes for UPR, alkyd resins and agricultural chemicals.',
    price: 115000,
    origin: 'Western India Region',
    warehouseId: 'wh-dahej',
    warehouseLabel: 'Dahej Hub',
    stock: 180,
    moq: 10,
    eta: '4–6 Days',
    badge: 'Best Value',
    casNumber: '108-31-6',
    applications: ['UPR', 'Alkyd Resins', 'Agrochemicals'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-25T08:00:00.000Z',
    popularityScore: 71,
    supplyOrigin: 'domestic',
    technicalSpecs: { purity: '99.5%', form: 'Flakes', meltingPoint: '52.8 °C' },
  }),
  blindGrade({
    id: 'mkt-melamine',
    name: 'Melamine Crystal Grade',
    grade: 'MEL',
    gradeCode: 'CHM-MEL-99',
    categoryId: 'chemicals',
    materialType: 'Melamine',
    subCategory: 'Intermediate',
    description: 'Melamine crystals for laminates, adhesives and flame-retardant resins.',
    price: 108000,
    origin: 'Northern India Region',
    warehouseId: 'wh-panipat',
    warehouseLabel: 'Panipat Hub',
    stock: 200,
    moq: 10,
    eta: '4–6 Days',
    badge: 'Best Value',
    casNumber: '108-78-1',
    applications: ['Laminates', 'Adhesives', 'FR Resins'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-26T08:00:00.000Z',
    popularityScore: 74,
    supplyOrigin: 'domestic',
    technicalSpecs: { purity: '99.8%', form: 'Crystals', moisture: '<0.1%' },
  }),
  blindGrade({
    id: 'mkt-caustic-soda',
    name: 'Caustic Soda Flakes 98%',
    grade: 'NaOH',
    gradeCode: 'CHM-CS-98',
    categoryId: 'chemicals',
    materialType: 'Caustic Soda',
    subCategory: 'Alkali',
    description: 'Caustic soda flakes for pulp & paper, textiles and water treatment.',
    price: 48500,
    origin: 'Western India Region',
    warehouseId: 'wh-dahej',
    warehouseLabel: 'Dahej Hub',
    stock: 1200,
    moq: 20,
    eta: '2–3 Days',
    badge: 'Lowest Cost',
    casNumber: '1310-73-2',
    applications: ['Pulp & Paper', 'Textiles', 'Water Treatment'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-27T08:00:00.000Z',
    popularityScore: 93,
    supplyOrigin: 'domestic',
    technicalSpecs: { purity: '98%', form: 'Flakes', naoh: '≥98%' },
  }),
  blindGrade({
    id: 'mkt-xylene',
    name: 'Mixed Xylene Solvent',
    grade: 'XYL',
    gradeCode: 'SOL-XYL-99',
    categoryId: 'chemicals',
    materialType: 'Xylene',
    subCategory: 'Aromatic Solvent',
    description: 'Mixed xylene for paints, coatings and petrochemical intermediate streams.',
    price: 81200,
    origin: 'Western India Region',
    warehouseId: 'wh-jamnagar',
    warehouseLabel: 'Western Hub',
    stock: 390,
    moq: 12,
    eta: '3–5 Days',
    badge: 'Best Value',
    casNumber: '1330-20-7',
    applications: ['Paints', 'Coatings', 'Intermediate'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-28T08:00:00.000Z',
    popularityScore: 69,
    supplyOrigin: 'domestic',
    technicalSpecs: { purity: '99%', form: 'Liquid', boilingRange: '137–143 °C' },
  }),
  blindGrade({
    id: 'mkt-n-butanol',
    name: 'n-Butanol Industrial',
    grade: 'NBA',
    gradeCode: 'SOL-NBA-99',
    categoryId: 'chemicals',
    materialType: 'n-Butanol',
    subCategory: 'Alcohol Solvent',
    description: 'n-Butanol for coatings, plasticizers and butyl acetate production.',
    price: 92500,
    origin: 'Western India Region',
    warehouseId: 'wh-hazira',
    warehouseLabel: 'Hazira Hub',
    stock: 260,
    moq: 10,
    eta: '3–5 Days',
    badge: 'High Demand',
    casNumber: '71-36-3',
    applications: ['Coatings', 'Plasticizers', 'Butyl Acetate'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-29T08:00:00.000Z',
    popularityScore: 65,
    supplyOrigin: 'domestic',
    technicalSpecs: { purity: '99.5%', form: 'Liquid', boilingPoint: '117.7 °C' },
  }),

  // ─── Recycled materials ─────────────────────────────────────────────────
  blindGrade({
    id: 'mkt-rpet-flake',
    name: 'rPET Hot Washed Flakes',
    grade: 'rPET',
    gradeCode: 'REC-PET-FL',
    categoryId: 'polymers',
    materialType: 'rPET',
    subCategory: 'Flakes',
    description: 'Hot-washed clear rPET flakes for sheet, fiber and bottle-to-bottle applications.',
    price: 72000,
    origin: 'Western India Region',
    warehouseId: 'wh-dahej',
    warehouseLabel: 'Dahej Hub',
    stock: 550,
    moq: 15,
    eta: '3–5 Days',
    badge: 'Lowest Cost',
    casNumber: '25038-59-9',
    applications: ['Sheet', 'Fiber', 'Bottle-to-Bottle'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-30T08:00:00.000Z',
    popularityScore: 89,
    supplyOrigin: 'domestic',
    technicalSpecs: { form: 'Flakes', iv: '0.72 dl/g', moisture: '<1%', color: 'Clear' },
  }),
  blindGrade({
    id: 'mkt-rhdpe-natural',
    name: 'rHDPE Natural Pellets',
    grade: 'rHDPE',
    gradeCode: 'REC-HDPE-NT',
    categoryId: 'polymers',
    materialType: 'rHDPE',
    subCategory: 'Pellets',
    description:
      'Natural rHDPE pellets from post-consumer drums for non-food containers and pipes.',
    price: 68500,
    origin: 'Western India Region',
    warehouseId: 'wh-hazira',
    warehouseLabel: 'Hazira Hub',
    stock: 420,
    moq: 16,
    eta: '3–5 Days',
    badge: 'Best Value',
    casNumber: '9002-88-4',
    applications: ['Non-Food Containers', 'Pipes', 'Crates'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-08-31T08:00:00.000Z',
    popularityScore: 80,
    supplyOrigin: 'domestic',
    technicalSpecs: { mfi: '0.4 g/10 min', density: '0.955 g/cm³', form: 'Pellets' },
  }),
  blindGrade({
    id: 'mkt-rldpe-film',
    name: 'rLDPE Film Regrind',
    grade: 'rLDPE',
    gradeCode: 'REC-LDPE-RG',
    categoryId: 'polymers',
    materialType: 'rLDPE',
    subCategory: 'Regrind',
    description: 'rLDPE film regrind for refuse bags, liners and secondary packaging film.',
    price: 62000,
    origin: 'Northern India Region',
    warehouseId: 'wh-panipat',
    warehouseLabel: 'Panipat Hub',
    stock: 380,
    moq: 18,
    eta: '4–6 Days',
    badge: 'Lowest Cost',
    casNumber: '9002-88-4',
    applications: ['Refuse Bags', 'Liners', 'Secondary Film'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-09-01T08:00:00.000Z',
    popularityScore: 77,
    supplyOrigin: 'domestic',
    technicalSpecs: { mfi: '0.8 g/10 min', density: '0.920 g/cm³', form: 'Regrind' },
  }),
  blindGrade({
    id: 'mkt-rpp-raffia',
    name: 'rPP Raffia Grade Pellets',
    grade: 'rPP',
    gradeCode: 'REC-PP-RF',
    categoryId: 'polymers',
    materialType: 'rPP',
    subCategory: 'Raffia',
    description: 'Recycled PP raffia pellets for woven sacks and non-critical injection parts.',
    price: 65500,
    origin: 'Western India Region',
    warehouseId: 'wh-jamnagar',
    warehouseLabel: 'Western Hub',
    stock: 310,
    moq: 15,
    eta: '3–5 Days',
    badge: 'Best Value',
    casNumber: '9003-07-0',
    applications: ['Woven Sacks', 'Injection Parts', 'Furniture'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-09-02T08:00:00.000Z',
    popularityScore: 78,
    supplyOrigin: 'domestic',
    technicalSpecs: { mfi: '4.0 g/10 min', density: '0.910 g/cm³', form: 'Pellets' },
  }),
  blindGrade({
    id: 'mkt-rabs-black',
    name: 'rABS Black Pellets',
    grade: 'rABS',
    gradeCode: 'REC-ABS-BK',
    categoryId: 'polymers',
    materialType: 'rABS',
    subCategory: 'Pellets',
    description: 'Black rABS from e-waste streams for appliance housings and non-visible parts.',
    price: 82000,
    origin: 'Northern India Region',
    warehouseId: 'wh-bathinda',
    warehouseLabel: 'Northern Hub',
    stock: 140,
    moq: 10,
    eta: '5–7 Days',
    badge: 'Limited Stock',
    casNumber: '9003-56-9',
    applications: ['Appliance Housings', 'Non-Visible Parts', 'Toys'],
    creditEligible: false,
    stockStatus: 'limited',
    createdAt: '2026-09-03T08:00:00.000Z',
    popularityScore: 59,
    supplyOrigin: 'domestic',
    technicalSpecs: { mfi: '10 g/10 min', density: '1.05 g/cm³', form: 'Pellets', color: 'Black' },
  }),

  // ─── Extra polymers / specialty ─────────────────────────────────────────
  blindGrade({
    id: 'mkt-pp-bopp',
    name: 'PP BOPP Film Grade',
    grade: 'PP',
    gradeCode: 'PP-BOPP-35',
    categoryId: 'polymers',
    materialType: 'Polypropylene',
    subCategory: 'BOPP Film',
    description: 'Homopolymer PP for biaxially oriented packaging film lines.',
    price: 101200,
    origin: 'Western India Region',
    warehouseId: 'wh-mundra',
    warehouseLabel: 'Mundra Hub',
    stock: 275,
    moq: 16,
    eta: '3–5 Days',
    badge: 'High Demand',
    casNumber: '9003-07-0',
    applications: ['BOPP Film', 'Labels', 'Lamination'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-09-04T08:00:00.000Z',
    popularityScore: 84,
    supplyOrigin: 'domestic',
    technicalSpecs: { mfi: '2.5–3.5 g/10 min', density: '0.905 g/cm³', form: 'Pellets' },
  }),
  blindGrade({
    id: 'mkt-pvc-paste',
    name: 'PVC Paste Resin P-450',
    grade: 'PVC',
    gradeCode: 'PVC-P-450',
    categoryId: 'polymers',
    materialType: 'PVC',
    subCategory: 'Paste / Emulsion',
    description: 'Emulsion PVC paste resin for artificial leather, flooring and coated fabrics.',
    price: 118500,
    origin: 'Western India Region',
    warehouseId: 'wh-dahej',
    warehouseLabel: 'Dahej Hub',
    stock: 130,
    moq: 8,
    eta: '4–6 Days',
    badge: 'Premium Grade',
    casNumber: '9002-86-2',
    applications: ['Artificial Leather', 'Flooring', 'Coated Fabrics'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-09-05T08:00:00.000Z',
    popularityScore: 67,
    supplyOrigin: 'domestic',
    technicalSpecs: { form: 'Powder', kValue: '70–74', viscosity: 'Paste grade' },
  }),
  blindGrade({
    id: 'mkt-pe-wax',
    name: 'PE Wax Micronized',
    grade: 'PEW',
    gradeCode: 'ADD-PEW-01',
    categoryId: 'additives',
    materialType: 'PE Wax',
    subCategory: 'Processing Aid',
    description: 'Micronized polyethylene wax for PVC processing, inks and masterbatch.',
    price: 135000,
    origin: 'Western India Region',
    warehouseId: 'wh-hazira',
    warehouseLabel: 'Hazira Hub',
    stock: 95,
    moq: 5,
    eta: '4–6 Days',
    badge: 'Premium Grade',
    casNumber: '9002-88-4',
    applications: ['PVC Processing', 'Inks', 'Masterbatch'],
    creditEligible: false,
    stockStatus: 'limited',
    createdAt: '2026-09-06T08:00:00.000Z',
    popularityScore: 60,
    supplyOrigin: 'domestic',
    technicalSpecs: { form: 'Powder', meltingPoint: '105–115 °C', particleSize: 'Micronized' },
  }),
  blindGrade({
    id: 'mkt-dotp',
    name: 'DOTP Plasticizer',
    grade: 'DOTP',
    gradeCode: 'ADD-DOTP-99',
    categoryId: 'additives',
    materialType: 'Plasticizer',
    subCategory: 'Non-Phthalate',
    description: 'Non-phthalate DOTP plasticizer for toys, medical and flexible PVC compounds.',
    price: 128500,
    origin: 'Western India Region',
    warehouseId: 'wh-mundra',
    warehouseLabel: 'Mundra Hub',
    stock: 165,
    moq: 8,
    eta: '3–5 Days',
    badge: 'High Demand',
    casNumber: '6422-86-2',
    applications: ['Toys', 'Medical PVC', 'Flexible Compounds'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-09-07T08:00:00.000Z',
    popularityScore: 79,
    supplyOrigin: 'domestic',
    technicalSpecs: { purity: '99.5%', form: 'Liquid', viscosity: '63 cP @ 20°C' },
  }),
  blindGrade({
    id: 'mkt-base-oil-sn500',
    name: 'Base Oil SN 500',
    grade: 'SN500',
    gradeCode: 'BO-GI-500',
    categoryId: 'base-oils',
    materialType: 'Base Oil',
    subCategory: 'Group I',
    description: 'Group I SN 500 bright stock blend component for gear and industrial oils.',
    price: 76500,
    origin: 'Western India Region',
    warehouseId: 'wh-jamnagar',
    warehouseLabel: 'Western Hub',
    stock: 280,
    moq: 12,
    eta: '3–5 Days',
    badge: 'Best Value',
    casNumber: '64742-52-5',
    applications: ['Gear Oils', 'Industrial Oils', 'Greases'],
    creditEligible: true,
    stockStatus: 'in_stock',
    createdAt: '2026-09-08T08:00:00.000Z',
    popularityScore: 73,
    supplyOrigin: 'domestic',
    technicalSpecs: { viscosity: '90–110 cSt @ 40°C', form: 'Liquid', vi: '90+' },
  }),
];

export function getBlindGradeById(id: string): MarketProduct | undefined {
  return blindGradesMock.find((product) => product.id === id);
}

export function getBlindGradesByMaterial(materialType: string): MarketProduct[] {
  return blindGradesMock.filter(
    (product) =>
      (product.materialType ?? product.category).toLowerCase() === materialType.toLowerCase(),
  );
}

export function getBlindGradeSubcategories(materialType: string): string[] {
  return Array.from(
    new Set(
      getBlindGradesByMaterial(materialType)
        .map((product) => product.subCategory)
        .filter((value): value is string => Boolean(value)),
    ),
  );
}
