export const brandColors = {
  navy: '#103460',
  primary: '#5B84B1',
  primaryDark: '#3D6A94',
  primaryLight: '#E8F1F8',
  primaryTint: '#F0F6FB',
  title: '#4E7CB0',
  tagline: '#7C99B8',
  muted: '#8E8E8E',
  body: '#4B5563',
  heading: '#1E3A5F',
  skip: '#666666',
  footer: '#999999',
  background: '#F5F7FA',
  surface: '#F9FAFB',
  white: '#FFFFFF',
  border: '#E5E7EB',
  borderFocus: '#5B84B1',
  inputLabel: '#6B7280',
  secondaryButton: '#6B7280',
  secondaryButtonDark: '#4B5563',
  indicatorInactive: '#D1D5DB',
  spinnerTrack: '#E5E7EB',
  illustrationLight: '#A8C4DE',
  illustrationMid: '#7BA3C9',
  illustrationDark: '#3D6A94',
  shield: '#2F5F8A',
  verified: '#3D7AB0',
  success: '#16A34A',
  successLight: '#DCFCE7',
  uploaded: '#E8F3FF',
  uploadedText: '#2563EB',
  badgeBg: '#E8F1F8',
  badgeText: '#3D6A94',
  overlay: '#E8ECF0',
  disabled: '#B0C4D8',
  disabledText: '#FFFFFF',
  link: '#5B84B1',
  error: '#EF4444',
  errorLight: '#FEE2E2',
  invoice: '#E11D48',
  notificationDot: '#EF4444',
  cardBlue: '#4A78B0',
  cardBlueDark: '#3A6496',
  bannerOverlay: 'rgba(16, 52, 96, 0.72)',
  otpCircuit: '#0F2744',
} as const;

export const colors = {
  light: {
    primary: brandColors.primary,
    primaryForeground: brandColors.white,
    secondary: '#F1F5F9',
    secondaryForeground: brandColors.navy,
    background: brandColors.white,
    foreground: brandColors.navy,
    muted: brandColors.background,
    mutedForeground: brandColors.muted,
    border: brandColors.border,
    destructive: brandColors.error,
    destructiveForeground: brandColors.white,
    success: brandColors.success,
    successForeground: brandColors.white,
    warning: '#F59E0B',
    warningForeground: brandColors.white,
    brand: brandColors,
  },
  dark: {
    primary: brandColors.primary,
    primaryForeground: brandColors.white,
    secondary: '#1E293B',
    secondaryForeground: '#F8FAFC',
    background: '#0F172A',
    foreground: '#F8FAFC',
    muted: '#1E293B',
    mutedForeground: '#94A3B8',
    border: '#334155',
    destructive: '#F87171',
    destructiveForeground: brandColors.white,
    success: '#4ADE80',
    successForeground: '#0F172A',
    warning: '#FBBF24',
    warningForeground: '#0F172A',
    brand: brandColors,
  },
} as const;

export type ThemeColorScheme = keyof typeof colors;

export type ThemeColors = (typeof colors)[ThemeColorScheme];

export type BrandColors = typeof brandColors;

export const getThemeColors = (scheme: ThemeColorScheme): ThemeColors => colors[scheme];
